### PR TITLE
WIP: Switch to new opencitations API

### PR DESCRIPTION
**Pull request by hellemo**
Initial port to new opencitations API.

TO DO:
- [x] Add back citation counts (not part of the metadata in this api)
- [x] Cleanup
- [x] Make sure tests work
- [x] Formatting

### CODE REVIEW

**Comment by AshtonSBradley** [comment]
Testing this branch, I find some DOI tests don't pass:

`14: @test julia.year == 2017 `

fails as there is no year field  in the new format it seems.

`19: show(io, MIME("text/html"), emjulia)`

fails, not sure why.

**Comment by hellemo** [comment]
> Testing this branch (main times out), I find some DOI tests don't pass:
> 
> `14: @test julia.year == 2017 `
> 
> fails as there is no year field in the new format it seems.

Thanks for testing. I think the main functionality is now in place, need to do some cleanup and make sure the tests pass still.

**Comment by stefanbringuier** [comment]
Tried running test as  well for commit https://github.com/hellemo/ShortCodes.jl/pull/12/commits/42dbc89c8d8cf48771ca59e07520eb0884b56bfe and as with @AshtonSBradley testing I'm seeing test fail but not due to 404 issue but due to 500 issues.

```julia
   Test threw exception
   Expression: length(split(julia.author, ";")) == 4
   HTTP.Exceptions.StatusError(500,"GET","/index/api/v1/metadata/10.1137/141000671",
...
...
```

**Comment by AshtonSBradley** [comment]
Tests pass for me now

**Pull request merged**
